name: cloud run preview


on: pull_request


jobs:
  build:
    runs-on: [self-hosted, netcup, zillowdata]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Inject keys
        run: echo -en '${{ secrets.KEYS_YAML_TESTS }}' >> keys.yaml

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3
          
      - name: Build Docker image
        run: |
          docker build -t zillow-data-collector .
          
      - name: Push Docker image to GCP Artifact Registry
        run: |
          gcloud auth configure-docker
          docker tag zillow-data-collector gcr.io/zillow-test-442918/zillow-data-collector:pr-preview-${{ github.event.number }}
          docker push gcr.io/zillow-test-442918/zillow-data-collector:pr-preview-${{ github.event.number }}
  preview:
    runs-on: [self-hosted, netcup, zillowdata]
    needs: build
    if: ${{ needs.build.result == 'success' }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3
          
      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'zillow-data-collector-qa'
          image: gcr.io/zillow-test-442918/zillow-data-collector:pr-preview-${{ github.event.number }}
          tag: pr-preview-${{ github.event.number }}
          region: us-central1
          flags: '--min-instances=0 --allow-unauthenticated'

      - name: Comment deployment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            A preview of this pull request has been deployed (or updated) at ${{ steps.deploy.outputs.url }}. 
          reactions: eyes, rocket
