name: cloud run deployment


on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed
    branches:
      - main
      - master
  workflow_dispatch: 


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Inject keys
        run: echo -en '${{ secrets.KEYS_YAML }}' >> keys.yaml

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Remove tests directory
        run: rm -r tests
      
      - name: Build Docker image
        run: |
          docker build -t zillow-data-collector .
          
      - name: Push Docker image to GCP Artifact Registry
        run: |
          gcloud auth configure-docker
          docker tag zillow-data-collector gcr.io/zillow-test-442918/zillow-data-collector
          docker push gcr.io/zillow-test-442918/zillow-data-collector
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}

    steps:
      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: zillow-data-collector
          image: gcr.io/zillow-test-442918/zillow-data-collector
          region: us-central1
          flags: '--min-instances=0 --allow-unauthenticated'

      - name: Update traffic to latest revision
        run: gcloud run services update-traffic zillow-data-collector --to-latest --region us-central1
