name: tests

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - docs/**/*.*
      - README.md
      - .github/workflows/google-cloud.yml
      - .github/workflows/deploy-preview.yml
      - .devcontainer/**/*.*
  pull_request:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: [self-hosted, netcup, zillowdata]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
        
      - name: Inject keys
        run: echo -en '${{ secrets.KEYS_YAML_TESTS }}' >> keys.yaml

      - name: Build Docker container
        run: docker build -t zillow-data-collector .
        
      - name: Run tests inside container
        run: docker run zillow-data-collector sh -c "pip install --no-cache-dir -r tests/requirements.txt && pytest"
